# Generated by Django 3.2.11 on 2022-04-21 14:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_collectdbook'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collectdbook',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
