# Generated by Django 3.2.11 on 2022-04-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_order_ordereditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordereditem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
