# Generated by Django 3.2.11 on 2022-04-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
